### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Phlosioneer** [jbeder/yaml-cpp#381] opened 2016-05-19 01:33 UTC
The documentation of this library seems woefully incomplete. CodeDocs / doxygen is a good start, but it only shows the structure of the project. It doesn't show any explanation of what classes do, what methods do, etc.

For an example, look [here](https://codedocs.xyz/jbeder/yaml-cpp/classYAML_1_1Emitter.html). There's no explanation of what the emitter class does, the details of the methods, whether there are any corner cases, how to detect and recover from errors... It doesn't even include the operator<< overloads for the class.

Looking at the actual file, there's also next to no comments to document the header file. The declaration list is separated into categories by some comments, that's it. No explanation of methods at all. No comments inside of template methods, either.

I would be willing to try and document a lot of the codebase - but I don't think I could do it without help, and I don't want to start working on something that might not even be wanted.

**Comment by jbeder** [comment] 2016-05-28 18:45
Yeah, I agree that the documentation is pretty bad. Always happy for patches with doc fixes.

Duplicate of #155

**Closed by jbeder** 2016-05-28 18:45 UTC

**Comment by Phlosioneer** [comment] 2016-05-28 20:00
I'be lost interest, sorry. This is a pretty quiet repo.
