### ISSUE TITLE
Support Merge Key Language Independent-Key

### ISSUE THREAD

**Issue by synacker** [jbeder/yaml-cpp#683] opened 2019-03-07 10:13 UTC
Yaml spec 1.1 has [Merge Key Language-Independent Type](https://yaml.org/type/merge.html)

Is it possible to parse this merge key from yaml-cpp?

**Comment by jbeder** [comment] 2019-03-07 15:17
Duplicate of #41

**Closed by jbeder** 2019-03-07 15:17 UTC
