### ISSUE TITLE
Using <<: to insert anchored map produces incorrect results

### ISSUE THREAD

**Issue by rdeits** [jbeder/yaml-cpp#353] opened 2016-01-12 00:03 UTC
For example, using the yaml file described in this SO answer: http://stackoverflow.com/a/9197237 

```yaml
Defaults: &defaults
  Company: foo
  Item: 123

Computer:
  <<: *defaults
  Price: 3000
```

in python, using the `yaml` package, I get (correctly): 

```
>>> config = yaml.load(open('Base.yaml'))
>>> print(config)
{'Computer': {'Item': 123, 'Price': 3000, 'Company': 'foo'}, 'Defaults': {'Item': 123, 'Company': 'foo'}}
```

(note that the Defaults map has been merged into the Computer map). 

but using `yaml-cpp`, the `<<` is interpreted as a map key, rather than inserting the contents of that map, so `config["Computer"]` gives: 

```
<<:
  Item: 123
  Company: foo
Price: 3000
```

**Comment by jbeder** [comment] 2016-01-12 14:42
This is a dupe of #41. Basically, merges are not required by the standard, there are some difficult questions to think about for the implementation, and so it's low priority.

**Closed by jbeder** 2016-01-12 14:42 UTC

**Comment by rdeits** [comment] 2016-01-12 21:13
Ah, okay. Sorry, I searched through the issue list but didn't see that one. My workaround was to define my own lookup method that treats '<<' as a default: 

```c++
YAML::Node get(YAML::Node parent, std::string key) {
  auto result = parent[key];
  if (result) {
    return result;
  } else {
    auto default_node = parent["<<"];
    if (default_node) {
      return get(default_node, key);
    } else {
      // No key, and no default, so return the null node as expected
      return result;
    }
  }
}
```
