### ISSUE TITLE
CMake fails on Arch Linux

### ISSUE THREAD

**Issue by msrd0** [jbeder/yaml-cpp#362] opened 2016-02-08 13:39 UTC
I have the yaml-cpp package from the official repo installed. As you can see [here](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/yaml-cpp), it is build with cmake with no changes to any file. I used `find_package(yaml-cpp REQUIRED)` and `target_link_library(foo ${YAML_CPP_LIBRARIES})` to link against yaml-cpp library. On running make, I was presented with the following error message:

    make[2]: *** No rule to make target '/build/yaml-cpp/src/yaml-cpp-release-0.5.3/libyaml-cpp.so.0.5.3', needed by 'foo'.  Stop.

After looking at what files the package came with, I found the file `/usr/lib/cmake/yaml-cpp/yaml-cpp-config.cmake`, that had an include to `<...>/yaml-cpp-targets.cmake`. By removing that import, everything works and my program is linked agains yaml-cpp. Is this a valid fix or does it break something? And if it breaks something, how should I resolve this issue?

I have version 0.5.3 installed.

**Comment by branoholy** [comment] 2016-03-10 23:46
I have the same problem and I've created a repo [branoholy/yaml-sample](https://github.com/branoholy/yaml-sample) to reproduce the bug.

**Comment by jbeder** [comment] 2016-03-26 19:17
Could this be solved by jbeder/yaml-cpp/pull/344?

**Comment by msrd0** [comment] 2016-03-26 23:39
@jbeder That pull request sounds good

**Comment by branoholy** [comment] 2016-03-27 01:27
@jbeder I tested it and it seems to be solved.

**Comment by jbeder** [comment] 2016-04-02 19:28
Fixed by #344.

**Closed by jbeder** 2016-04-02 19:28 UTC
