### ISSUE TITLE
Merge functionality - status request

### ISSUE THREAD

**Issue by developer-andre** [jbeder/yaml-cpp#638] opened 2018-11-06 11:47 UTC
I like to know the current status of the merge functionality.

I have read #300 and would like to know -very broadly- when it is expected to work. 2018? 2019?

(Because the latest version already handles the merge key (<<) and the existence of #300 I decided to create an issue instead of a general question on stackoverflow)

**Comment by jbeder** [comment] 2023-01-17 22:58
Dupe of #41

**Closed by jbeder** 2023-01-17 22:58 UTC
