### ISSUE TITLE
Crash on accessing nonexistent node in yaml-cpp 0.5.2

### ISSUE THREAD

**Issue by sfalexrog** [jbeder/yaml-cpp#308] opened 2015-04-29 09:47 UTC
I have the following code:

    #include <yaml-cpp/yaml.h>
    #include <iostream>

    int main(int argc, char* argv[])
    {
        YAML::Node empty = YAML::Load("");
        if (empty["unavailable"]) {
            std::cout << "This shouldn't happen" << std::endl;
        } else {
            std::cout << "No such node" << std::endl;
        }
        return 0;
    }

If I understand correctly, this code should output the string "No such node", and indeed it does in 0.5.1. In 0.5.2 it fails with access violation reading a null pointer.

I'm using statically-linked libraries with Debug and RelWithDebInfo, built with MSVS2013 and Boost 1.57.0.

The code fails in YAML::detail::node_data::get(), in 

    for(node_map::const_iterator it = m_map.begin(); it != m_map.end(); ++it) {
        /*...*/
    }

Additionally, I've tried building a project that uses yaml-cpp (namely, OpenXcom) for Android with yaml-cpp 0.5.2, and apparently the resulting binary fails when checking for a key that doesn't exist (it works with 0.5.1).

Could it be some kind of a configuration mistake on my part or a misinterpretation of how checking for elements should work?

**Comment by jbeder** [comment] 2015-04-29 13:09
I suspect this is a duplicate of #286. Can you sync to head and check if this is still a crash?

**Comment by sfalexrog** [comment] 2015-05-01 11:56
Yup, tried that and it worked. However, I've been running into other issues as well, hitting #305 and having issues with empty sequences. Should I open a separate issue for that?

**Comment by jbeder** [comment] 2015-05-01 13:24
If there's a separate bug, then yes, please :)

**Comment by jbeder** [comment] 2015-05-01 13:25
Closing this as a duplicate of #286.

**Closed by jbeder** 2015-05-01 13:25 UTC
