### ISSUE TITLE
Inconsistency between setting node value versus scalar value

### ISSUE THREAD

**Issue by md5i** [jbeder/yaml-cpp#329] opened 2015-08-13 14:43 UTC
Observe the following code:

    #include <yaml-cpp/yaml.h>
    
    using namespace YAML;
    
    int main()
    {
      Node node;
      Node k1("k1");
      Node k2("k2");
      Node v1("v1");
      Node v2("v2");
    
      /* Create a map of k1 -> v1 and k2 -> v1 */
      node[k1] = v1;
      node[k2] = v1;
      std::cout << node << '\n' << std::endl;
    
      /* Set k2 -> v2 */
      node[k2] = v2;
      std::cout << node << '\n' << std::endl;
    
      /* Set k2 back to v1 */
      node[k2] = v1;
      std::cout << node << '\n' << std::endl;
    
      /* Set k2 -> "xx" */
      node[k2] = "xx";
      std::cout << node << '\n' << std::endl;
    }

After creating the initial map, we get the following:

    k1: &1 v1
    k2: *1

Setting k2 to v2 works as expected:

    k1: v1
    k2: v2

Returning k2 to v1 also works as expected:

    k1: &1 v1
    k2: *1

But let's try setting k1's value to a scalar!

    k1: &1 xx
    k2: *1

We have actually modified v1 to be xx.  Now either behavior here could be considered reasonable, but the current mix of behaviors (setting a scalar as opposed to a node) seems inconsistent.  I would either expect the last version to be `{k1: xx, k2: v1}` or the second one to be `{k1: &1 v2, k2: *1}`.

**Comment by jbeder** [comment] 2015-08-25 03:58
Yeah, I totally agree. I highlighted the issue a while ago in Issue 208, but I haven't come up with a satisfactory solution.

**Comment by jbeder** [comment] 2015-08-25 03:58
Closing as duplicate of #208.

**Closed by jbeder** 2015-08-25 03:58 UTC
