### ISSUE TITLE
Anchor/Alias crashs on accessing not overridden key/value

### ISSUE THREAD

**Issue by hofbi** [jbeder/yaml-cpp#617] opened 2018-08-30 21:02 UTC
My yaml file has the following structure

```yaml
a_root: &root_anchor
  key1: value1
  key2: value2
b_child:
  <<: *root_anchor
  key2: value2_override
```
If I evaluate this file with [yamllint.com](http://www.yamllint.com/) or [pyyaml](https://pyyaml.org/) this results into
```yaml
a_root: 
  key1: value1
  key2: value2
b_child: 
  key1: value1
  key2: value2_override
```
But If I try to access the value of `[b_child][key1]` this result in a crash as `key1` does not exit for `b_child`

This issue could be related to #312 and #110

**Comment by jbeder** [comment] 2018-09-03 15:11
What do you mean "results in a crash"? Is it a segfault or an exception?

(I suspect that what you're seeing is that yaml-cpp doesn't support merge keys. See #41 )

**Comment by hofbi** [comment] 2018-09-03 20:48
Yeah you are right. It's an exception

```shell
unknown file: Failure
FailureC++ exception with description "bad conversion" thrown in the test body.
```

And looks quite simmilar to #41. Within #41 PR #300 is linked which should fix it. But I am not sure if this will also fix this issue. I added a comment with a test suggestion to check if PR #300 will also fix this issue (see https://github.com/jbeder/yaml-cpp/pull/300#issuecomment-418190825)

**Comment by jbeder** [comment] 2018-09-03 20:58
Sounds good. I'm going to close this as a duplicate of #41.

**Closed by jbeder** 2018-09-03 20:58 UTC
